version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.9.4
      - image: redis:3.0.7-alpine
    working_directory: /go/src/github.com/nktn/ts-dakoku
    steps:
      - checkout
      - run: make test
      - run: go get github.com/mattn/goveralls
      - run: go get github.com/schrej/godacov
      - run: goveralls -coverprofile=coverage/cover.out -service=circle-ci
      - run: godacov -t $CODACY_PROJECT_TOKEN -r ./coverage/cover.out -c $CIRCLE_SHA1
      - store_artifacts:
          path: coverage
          destination: coverage

  deploy:
    docker:
      - image: atsnngs/alpine-heroku-cli:latest
    working_directory: /go/src/github.com/nktn/ts-dakoku
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '4d:74:c3:f5:28:7d:ed:db:aa:b8:6c:7d:15:98:8a:5b'
      - run: /bin/sh /setup.sh
      - run: git push heroku master

workflows:
  version: 2
  test:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only: [master, deploy]
          requires:
            - test
